print("--Menu--")
print("1.Gestion de jugadores")
print("2.Gestion de Mundos Virtuales")
print("3.Inventario de los jugadores")
print("4.Gestion de Batallas y partidas")
print("5.Ranking Globals")
print("6.Gestion de Equipo")
print("7.Consultas de jugador")
print("8.salir")

print("\n")
print("--Gestion de Jugadores--")
print("1.Registro")
print("2.Modificacion")
print("3.Eliminacion")
print("4.Consulta de jugadores")
print("5.salir")

print("\n")
print("--Gestion de Mundos Virtuales--")
print("1.Crear un mundo")
print("2.Asociar mundos")
print("3.Ver mundos y asociaciones")
print("4.Eliminar un mundo")
print("5.salir")

print("\n")
print("--Inventario de los jugadores--")
print("1.Crear inventario")
print("2.Añadir objeto a inventario")
print("3.Actualizar cantidad de objeto")
print("4.Eliminar objeto")
print("5.salir")

print("\n")
print("--Gestion de Batallas y partidas--")
print("1.Batalla rapida")
print("2.Ver historial de batallas")
print("3.salir")

print("\n")
print("--Ranking Global--")
print("1.Ver Ranking")
print("5.salir")

print("\n")
print("--Gestion de Equipo--")
print("1.Unirse a un equipo")
print("2.Estadisticas del equipo")
print("3.salir")

print("\n")
print("--Consultas de jugador--")
print("1.Top 10 jugadores")
print("2.Inventario de jugador(ID)")
print("3.Historial de un jugador(ID)")
print("4.salir")

